<!DOCTYPE html>
<html>
<head>
    <title>Edit AI Draft</title>
    <style>
        body { font-family: 'Segoe UI', sans-serif; background-color: #f4f7f6; }
        .container { max-width: 900px; margin: 40px auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
        textarea { width: 100%; height: 500px; padding: 20px; border: 1px solid #ccc; border-radius: 4px; font-family: 'Courier New', Courier, monospace; font-size: 14px; line-height: 1.6; box-sizing: border-box; }
        .toolbar { display: flex; justify-content: space-between; margin-bottom: 20px; align-items: center; }
        .btn { padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; text-decoration: none; }
        .btn-save { background-color: #28a745; color: white; }
        .btn-back { background-color: #6c757d; color: white; }
    </style>
</head>
<body>
<div class="container">
    <div class="toolbar">
        <h1>Review AI Draft</h1>
        <div>
            <a href="?action=index" class="btn btn-back">&larr; Start Over</a>
            <button class="btn btn-save" onclick="window.print()">Print Letter</button>
        </div>
    </div>

    <p style="color: #666;">You can edit the text below before printing. The AI has generated this based on the agreement details.</p>

    <textarea id="letter_body"><?= htmlspecialchars($draft) ?></textarea>

    <div style="margin-top: 20px; font-size: 12px; color: #999;">
        * This letter was generated by AI. Please verify all facts and figures before signing.
    </div>
</div>
</body>
</html>
