extension_dir = "C:\Users\arvin\php\ext"
extension=curl
extension=gd
extension=mbstring
extension=openssl
extension=pdo_pgsql
extension=pgsql
extension=fileinfo

[Session]
session.save_path = "e:\Research\ModPyPhp\sessions_new"

